# Swagger configuration file

# values in the swaggerNode hash are system configuration for Swagger
swaggerNode:
  docEndpoints:
    raw: /swagger

# any other values in this file are just loaded into the config for application access...
